version: '3.9'

services:
  backend:
    build: ./backend
    container_name: gitterbox-backend
    environment:
      - JWT_SECRET=${JWT_SECRET:-gitterbox-secret}
    volumes:
      - ./data:/data
    expose:
      - "5001"
    restart: unless-stopped

  frontend:
    image: nginx:1.27-alpine
    container_name: gitterbox-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5000:80"
    depends_on:
      - backend
    restart: unless-stopped
